name: riber

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: riber-pgsql-dev
    environment:
      POSTGRES_DB: riber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: runtime
    container_name: riber-api-dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  data-dev:

networks:
  default:
    name: network-dev