# Etapa 1 - Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /build

RUN apt-get update && apt-get install -y \
    nano bash dos2unix tzdata openssl curl \
    && rm -rf /var/lib/apt/lists/*

COPY Directory.Packages.props ./
COPY Directory.Build.props ./
COPY Riber.slnx ./

COPY src/Riber.Api/Riber.Api.csproj ./src/Riber.Api/
COPY src/Riber.Application/Riber.Application.csproj ./src/Riber.Application/
COPY src/Riber.Domain/Riber.Domain.csproj ./src/Riber.Domain/
COPY src/Riber.Infrastructure/Riber.Infrastructure.csproj ./src/Riber.Infrastructure/
COPY tests/Riber.Application.Tests/Riber.Application.Tests.csproj ./tests/Riber.Application.Tests/
COPY tests/Riber.Domain.Tests/Riber.Domain.Tests.csproj ./tests/Riber.Domain.Tests/
COPY tests/Riber.Infrastructure.Tests/Riber.Infrastructure.Tests.csproj ./tests/Riber.Infrastructure.Tests/
RUN dotnet restore Riber.slnx

COPY . .
RUN dotnet build Riber.slnx -c Debug --no-restore
RUN dotnet test Riber.slnx --no-build --no-restore
RUN dotnet publish src/Riber.Api/Riber.Api.csproj -c Debug -o /app/publish --no-build --no-restore

# Etapa 2 - Migration Stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migration
WORKDIR /src

RUN apt-get update && apt-get install -y postgresql-client netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY --from=build /build .
COPY infra/scripts/apply-migrations.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/apply-migrations.sh

# Etapa 3 - Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
COPY --from=build /app/publish .

COPY infra/scripts/generate-certificates.sh /usr/local/bin/
COPY infra/scripts/startup.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/*.sh

ENTRYPOINT ["/usr/local/bin/startup.sh"]