name: riber

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: riber-pgsql-dev
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME:-riber_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "5432:5432"
    volumes:
      - riber-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.dev
      target: migration
    container_name: riber-migration-dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.dev
    command: ["/usr/local/bin/apply-migrations.sh"]

  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.dev
      target: runtime
    container_name: riber-api-dev
    depends_on:
      migration:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  riber-data-dev:

networks:
  default:
    name: riber-network-dev