// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Riber.Infrastructure.Persistence;

#nullable disable

namespace Riber.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250722011343_AddPermissionTableWithSeeders")]
    partial class AddPermissionTableWithSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Riber.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_company_id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Riber.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_user_id");

                    b.HasIndex(new[] { "CompanyId" }, "ix_user_company_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationPermission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_application_permissions_id");

                    b.ToTable("application_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "Companies",
                            Description = "Criar empresas",
                            IsActive = false,
                            Name = "companies.create"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Companies",
                            Description = "Ver empresas",
                            IsActive = false,
                            Name = "companies.read"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Companies",
                            Description = "Editar empresas",
                            IsActive = false,
                            Name = "companies.update"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Companies",
                            Description = "Excluir empresas",
                            IsActive = false,
                            Name = "companies.delete"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Companies",
                            Description = "Gerenciar usuários da empresa",
                            IsActive = false,
                            Name = "companies.manage_users"
                        },
                        new
                        {
                            Id = 201,
                            Category = "Orders",
                            Description = "Criar pedidos",
                            IsActive = false,
                            Name = "orders.create"
                        },
                        new
                        {
                            Id = 202,
                            Category = "Orders",
                            Description = "Ver pedidos",
                            IsActive = false,
                            Name = "orders.read"
                        },
                        new
                        {
                            Id = 203,
                            Category = "Orders",
                            Description = "Editar pedidos",
                            IsActive = false,
                            Name = "orders.update"
                        },
                        new
                        {
                            Id = 204,
                            Category = "Orders",
                            Description = "Excluir pedidos",
                            IsActive = false,
                            Name = "orders.delete"
                        },
                        new
                        {
                            Id = 205,
                            Category = "Orders",
                            Description = "Aprovar pedidos",
                            IsActive = false,
                            Name = "orders.approve"
                        },
                        new
                        {
                            Id = 301,
                            Category = "Products",
                            Description = "Cadastrar produtos",
                            IsActive = false,
                            Name = "products.create"
                        },
                        new
                        {
                            Id = 302,
                            Category = "Products",
                            Description = "Visualizar produtos",
                            IsActive = false,
                            Name = "products.read"
                        },
                        new
                        {
                            Id = 303,
                            Category = "Products",
                            Description = "Editar produtos",
                            IsActive = false,
                            Name = "products.update"
                        },
                        new
                        {
                            Id = 304,
                            Category = "Products",
                            Description = "Remover produtos",
                            IsActive = false,
                            Name = "products.delete"
                        },
                        new
                        {
                            Id = 305,
                            Category = "Products",
                            Description = "Importar produtos",
                            IsActive = false,
                            Name = "products.import"
                        },
                        new
                        {
                            Id = 401,
                            Category = "Users",
                            Description = "Criar usuários",
                            IsActive = false,
                            Name = "users.create"
                        },
                        new
                        {
                            Id = 402,
                            Category = "Users",
                            Description = "Visualizar usuários",
                            IsActive = false,
                            Name = "users.read"
                        },
                        new
                        {
                            Id = 403,
                            Category = "Users",
                            Description = "Editar usuários",
                            IsActive = false,
                            Name = "users.update"
                        },
                        new
                        {
                            Id = 404,
                            Category = "Users",
                            Description = "Remover usuários",
                            IsActive = false,
                            Name = "users.delete"
                        },
                        new
                        {
                            Id = 405,
                            Category = "Users",
                            Description = "Atribuir funções aos usuários",
                            IsActive = false,
                            Name = "users.assign_roles"
                        },
                        new
                        {
                            Id = 501,
                            Category = "Reports",
                            Description = "Visualizar relatórios",
                            IsActive = false,
                            Name = "reports.view"
                        },
                        new
                        {
                            Id = 502,
                            Category = "Reports",
                            Description = "Exportar relatórios",
                            IsActive = false,
                            Name = "reports.export"
                        },
                        new
                        {
                            Id = 503,
                            Category = "Reports",
                            Description = "Agendar relatórios",
                            IsActive = false,
                            Name = "reports.schedule"
                        },
                        new
                        {
                            Id = 601,
                            Category = "Settings",
                            Description = "Visualizar configurações",
                            IsActive = false,
                            Name = "settings.view"
                        },
                        new
                        {
                            Id = 602,
                            Category = "Settings",
                            Description = "Alterar configurações",
                            IsActive = false,
                            Name = "settings.update"
                        },
                        new
                        {
                            Id = 701,
                            Category = "Roles",
                            Description = "Criar perfis de acesso",
                            IsActive = false,
                            Name = "roles.create"
                        },
                        new
                        {
                            Id = 702,
                            Category = "Roles",
                            Description = "Visualizar perfis de acesso",
                            IsActive = false,
                            Name = "roles.read"
                        },
                        new
                        {
                            Id = 703,
                            Category = "Roles",
                            Description = "Editar perfis de acesso",
                            IsActive = false,
                            Name = "roles.update"
                        },
                        new
                        {
                            Id = 704,
                            Category = "Roles",
                            Description = "Excluir perfis de acesso",
                            IsActive = false,
                            Name = "roles.delete"
                        },
                        new
                        {
                            Id = 705,
                            Category = "Roles",
                            Description = "Atribuir permissões aos perfis",
                            IsActive = false,
                            Name = "roles.assign_permissions"
                        });
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_aspnet_role_normalized_name");

                    b.ToTable("aspnet_role", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_aspnet_role_claim_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_aspnet_role_claim_role_id");

                    b.ToTable("aspnet_role_claim", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<Guid>("UserDomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_domain_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_user_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_aspnet_user_normalized_user_name");

                    b.HasIndex(new[] { "UserDomainId" }, "ix_aspnet_user_user_domain_id")
                        .IsUnique();

                    b.ToTable("aspnet_user", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_aspnet_user_claim_user_id");

                    b.ToTable("aspnet_user_claim", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey")
                        .HasName("pk_aspnet_user_login_user_id_login_provider_provider_key");

                    b.ToTable("aspnet_user_login", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_aspnet_user_role_user_id_role_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_aspnet_user_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_aspnet_user_role_user_id");

                    b.ToTable("aspnet_user_role", (string)null);
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_aspnet_user_token_user_id_login_provider_name");

                    b.ToTable("aspnet_user_token", (string)null);
                });

            modelBuilder.Entity("Riber.Domain.Entities.Company", b =>
                {
                    b.OwnsOne("Riber.Domain.ValueObjects.TaxId.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tax_id_type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("text")
                                .HasColumnName("tax_id_value");

                            b1.HasKey("CompanyId");

                            b1.HasIndex(new[] { "Value" }, "uq_company_tax_id")
                                .IsUnique();

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Riber.Domain.ValueObjects.CompanyName.CompanyName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Corporate")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("text")
                                .HasColumnName("corporate_name")
                                .HasAnnotation("MinLength", (byte)3);

                            b1.Property<string>("Fantasy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("text")
                                .HasColumnName("fantasy_name")
                                .HasAnnotation("MinLength", (byte)3);

                            b1.HasKey("CompanyId");

                            b1.HasIndex(new[] { "Corporate" }, "uq_company_corporate_name");

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Riber.Domain.ValueObjects.Email.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("CompanyId");

                            b1.HasIndex(new[] { "Value" }, "uq_company_email")
                                .IsUnique();

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Riber.Domain.ValueObjects.Phone.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("text")
                                .HasColumnName("phone");

                            b1.HasKey("CompanyId");

                            b1.HasIndex(new[] { "Value" }, "uq_company_phone")
                                .IsUnique();

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("Riber.Domain.Entities.User", b =>
                {
                    b.HasOne("Riber.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Riber.Domain.ValueObjects.TaxId.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tax_id_type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("text")
                                .HasColumnName("tax_id_value");

                            b1.HasKey("UserId");

                            b1.HasIndex(new[] { "Value" }, "uq_user_tax_id")
                                .IsUnique();

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Riber.Domain.ValueObjects.FullName.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("text")
                                .HasColumnName("full_name");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Company");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("Riber.Infrastructure.Persistence.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Riber.Domain.Entities.User", "UserDomain")
                        .WithOne()
                        .HasForeignKey("Riber.Infrastructure.Persistence.Identity.ApplicationUser", "UserDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDomain");
                });
#pragma warning restore 612, 618
        }
    }
}
